### ISSUE TITLE
Building error with VTK

### ISSUE THREAD

**Issue by ililikakis** [DLR-AMR/t8code#550]
Building t8code with VTK enabled is not posssible:
`undefined reference to symbol '_ZN22vtkCellDataToPointData3NewEv'`

The error comes from the file `config/t8_vtk.m4`

Changing line 33 to 37 into an older state:
```
    T8_VTK_LIBS="-lvtkIOXML-$t8_vtk_version -lvtkCommonExecutionModel-$t8_vtk_version \   
    -lvtkCommonDataModel-$t8_vtk_version -lvtkIOGeometry-$t8_vtk_version -lvtkIOXMLParser-$t8_vtk_version \
    -lvtkIOParallelXML-$t8_vtk_version -lvtkIOPLY-$t8_vtk_version -lvtkParallelMPI-$t8_vtk_version \
    -lvtkFiltersCore-$t8_vtk_version -lvtksys-$t8_vtk_version \
    -lvtkCommonCore-$t8_vtk_version -lvtkzlib-$t8_vtk_version -lvtkIOLegacy-$t8_vtk_version"
```
fixes the problem.

**Comment by Davknapp** [comment]
This bug does not occur on the main branch, but on the branch cmesh_vtk_reader_implementation

**Comment by Davknapp** [comment]
Thanks for directly posting the solution ;) I will have a closer look at it

**Comment by ililikakis** [comment]
Oh, sorry. I did not double checked this.  After merging `main` into my branche `featur-vtk_DataSet_PointSet_translator` the error has also occurred. That's why I wrongly assumed it.
